[project]
name = "odisse-challenge26"
version = "0.1.0"
description = "Datavisualisation interactive sur les inégalités sociales et territoriales de santé"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dash>=4.4.1",
    "geojson-rewind>=1.2.1",
    "gunicorn>=26.2.0",
    "pandas>=3.0.6",
    "plotly>=7.1.0",
]
