---
title: "Construction de la base communale des indicateurs territoriaux"
format: html
---

# Packages

```{r}
library(tidyverse)
library(readxl)
```

# Importation des données 

## FDep20

```{r}
fdep <-read.csv(
  "~/projects/Odisse_Challenge26/data/raw/indice-de-defavorisation-sociale-fdep-par-commune.csv",
  header = TRUE,
  sep = ","
) |>
  mutate(
    Code.commune = as.character(Code.commune)
  )
```


## F-EDI

```{r}
fedi <- read.csv(
  "~/projects/Odisse_Challenge26/data/raw/french-european-deprivation-index-f-edi-2021-par-commune.csv",
  header = TRUE,
  sep = ","
  ) |>
  mutate(
    Commune.Code = as.character(Commune.Code)
  )
```

## APL

```{r}
apl <- read_excel(
  "~/projects/Odisse_Challenge26/data/raw/apl.xlsx",
  sheet = "Data",
  skip = 4
) %>%
  rename(
    code_commune = codgeo,
    commune = libgeo,
    annee = an,
    apl = apl_mg_hmep
  ) %>%
  mutate(
    code_commune = as.character(code_commune),
    commune = as.character(commune),
    annee = as.integer(annee),
    apl = as.numeric(apl)
  ) %>%
  filter(!is.na(apl))
```

## Base annexe : population 2023

```{r}
population_2023 <-read.csv(
  "~/projects/Odisse_Challenge26/data/raw/donnees_communes.csv",
  header = TRUE,
  sep = ";"
  ) %>%
  rename(
    code_commune = COM,
    commune = Commune,
    population_totale = PTOT
  ) %>%
  mutate(
    code_commune = as.character(code_commune),
    commune = as.character(commune),
    population_totale = as.numeric(population_totale)
  )
```

# FDep20 + F-EDI

```{r}
territoires <- fdep |>
  inner_join(
    fedi,
    by = c("Code.commune" = "Commune.Code")
  )
```

# Nettoyage de la géographie 

```{r}
territoires <- territoires |>
  transmute(

    # Identifiant communal
    code_commune = Code.commune,

    # Commune
    commune = Commune,

    # Géographie départementale
    code_departement = Département.Code,
    departement = Département.x,

    # Géographie régionale
    code_region = Région.Code.x,
    region = Région.x,

    # FDep20
    fdep = as.numeric(Indice.de.défavorisation.en.quintiles),

    # F-EDI
    EDI = as.numeric(EDI),

    # Autres informations F-EDI
    quintile_edi = Quintile.natonal,
    millesime_edi = Millésime.EDI
  )
```

## Ajout de l'APL et de la population

```{r}
apl_population <- apl |>
  left_join(
    population_2023 |>
      select(
        code_commune, 
        population_totale
        ),
    by = "code_commune"
  )
```

```{r}
territoires <- territoires |>
  left_join(
    apl_population |>
      select(
        code_commune,
        population_totale,
        apl
      ),
    by = "code_commune"
  )
```

# Variables territoriales standardisées

```{r}
territoires <- territoires |>
  mutate(
    z_fdep = as.numeric(
      scale(fdep)
    ),
    z_fedi = as.numeric(
      scale(EDI)
    ),
    ecart_indices = z_fedi - z_fdep
  )
```

# Contrôle des doublons

```{r}
# valeurs manquantes et doublons
controle_doublons <- territoires |>
  summarise(
    nb_lignes = n(),
    nb_communes = n_distinct(code_commune)
  )

print(controle_doublons)
```
# Contrôle des données manquantes
```{r}
controle_manquants <- territoires |>
  summarise(
    nb_communes = n_distinct(code_commune),
    nb_apl_manquante = sum(is.na(apl)),
    nb_population_manquante = sum(is.na(population_totale)),
    nb_fedi_manquante = sum(is.na(EDI)),
    nb_fdep_manquante = sum(is.na(fdep)),
    nb_region_manquante = sum(is.na(region)),
    nb_departement_manquant = sum(is.na(departement))
  )

print(controle_manquants)
```

# Contrôle de la géographie

```{r}
territoires |>
  summarise(
    nb_regions = n_distinct(region),
    nb_departements = n_distinct(departement)
  )
```

# Quelques statistiques descriptives

```{r}
territoires |>
  summarise(
    apl_min = min(apl, na.rm = TRUE),
    apl_mediane = median(apl, na.rm = TRUE),
    apl_moyenne = mean(apl, na.rm = TRUE),
    apl_max = max(apl, na.rm = TRUE),
    
    population_totale = sum(population_totale, na.rm = TRUE)
  )
```

# Export

```{r}
write_csv(
  territoires,
  "~/projects/Odisse_Challenge26/data/processed/territoires_communes.csv"
)
```


